version: '2.1'

services:
  notificaciones-ms:
    build: ./notificaciones-ms
    env_file: 
      - ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on: 
      notificaciones-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I notificaciones-ms:${APP_PORT}/notificaciones --fail"
      interval: 20s
      retries: 10
    links: 
      - notificaciones-db:notificaciones-db
    restart: on-failure

  notificaciones-db:
    # build: ./notificaciones-db/
    image: mariadb:10.3.14
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    env_file: 
      - ./.env
    volumes: 
      - ./notificaciones-db/SQL_Script.sql:/docker-entrypoint-initdb.d/SQL_Script.sql
      - ${MYSQL_DATA_VOLUME}:/var/lib/mysql
    ports: 
      - ${MYSQL_PORT}:3306
    restart: always
